/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicalfile;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author gloria
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    String role;
    static Statement stmt = null;
    static Connection conn = null;
    String pass, user, roleType;
    int row;

    public AddUser(String role, Statement stmt) {
        initComponents();
        setSize(580, 450);
        this.role = role;
        this.stmt = stmt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jUserNameTextField = new javax.swing.JTextField();
        jPasswordTextField = new javax.swing.JTextField();
        jRoleComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAdd.setText("Προσθήκη");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd);
        jButtonAdd.setBounds(110, 330, 110, 50);

        jButtonLogOut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonLogOut.setText("Αποσύνδεση");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogOut);
        jButtonLogOut.setBounds(390, 330, 110, 50);

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDelete.setText("Διαγραφή");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete);
        jButtonDelete.setBounds(250, 330, 110, 50);
        getContentPane().add(jUserNameTextField);
        jUserNameTextField.setBounds(240, 110, 120, 20);
        getContentPane().add(jPasswordTextField);
        jPasswordTextField.setBounds(240, 160, 120, 20);

        jRoleComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRoleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Secretary", "Nurse", "Doctor", "Administrator" }));
        getContentPane().add(jRoleComboBox);
        jRoleComboBox.setBounds(240, 200, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("~ Εγγραφή Νέου Χρήστη ~");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 10, 390, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ρόλος :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 210, 70, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Κωδικός :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 160, 80, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Αναγνωριστικό χρήστη :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 110, 160, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalfile/newpackage/Medical_2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 570, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Authentication(stmt, conn).setVisible(true);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        this.user = jUserNameTextField.getText();
        this.pass = jPasswordTextField.getText();
        this.roleType = (String) jRoleComboBox.getSelectedItem();
        addition(stmt, user, pass, roleType);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:       
        this.user = jUserNameTextField.getText();
        this.pass = jPasswordTextField.getText();
        this.roleType = (String) jRoleComboBox.getSelectedItem();
        System.out.println(delete(stmt, user, pass, roleType));
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    public String addition(Statement stmt, String user, String pass, String roleType) {

        if (stmt != null) {
            try {
                String sql;
                sql = "INSERT INTO user (username, password, role) VALUES ('" + user + "','" + pass + "','" + roleType + "');";
                System.out.println(sql);
                stmt.executeUpdate(sql);
            } catch (SQLException es) {
                System.out.println("Unable to insert int the databese");
                JOptionPane.showMessageDialog(null, "Μη ολοκληρωμένα πεδία.", "Ανεπιτυχής Δημιουργία", JOptionPane.ERROR_MESSAGE);
                return "ERROR";
            }

            if (stmt == null) {
                JOptionPane.showMessageDialog(null, "Μη ολοκληρωμένα πεδία.", "Ανεπιτυχής Δημιουργία", JOptionPane.ERROR_MESSAGE);
                return "ERROR";
            } else {
                JOptionPane.showMessageDialog(null, "Ο νέος χρήστης προστέθηκε.", "Επιτυχής Προσθήκη", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        return "Added";
    }

    public String delete(Statement stmt, String user, String pass, String roleType) {

        if (stmt != null) {
            try {
                String sql;
                sql = "DELETE FROM user WHERE username= '" + user + "' AND password = '" + pass + "' AND role='" + roleType + "';";
                this.row = stmt.executeUpdate(sql);

            } catch (SQLException es) {
                System.out.println("Unable to insert into the databese");
                JOptionPane.showMessageDialog(null, "Μη ολοκληρωμένα πεδία.", "Ανεπιτυχής Δημιουργία", JOptionPane.ERROR_MESSAGE);
            }

            if (stmt == null) {
                JOptionPane.showMessageDialog(null, "Μη ολοκληρωμένα πεδία.", "Ανεπιτυχής Δημιουργία", JOptionPane.ERROR_MESSAGE);
                return "ERROR";
            } else if (row == 0) {
                JOptionPane.showMessageDialog(null, "Δεν υπάρχει ο χρήστης.", "Ανεπιτυχής Διαγραφή", JOptionPane.INFORMATION_MESSAGE);
                return "This user does not exist";
            } else {
                JOptionPane.showMessageDialog(null, "Ο χρήστης διαγράφηκε επιτυχώς.", "Επιτυχής Διαγραφή", JOptionPane.INFORMATION_MESSAGE);
                return "Deleted";
            }
        }
        return "ERROR";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jPasswordTextField;
    private javax.swing.JComboBox jRoleComboBox;
    private javax.swing.JTextField jUserNameTextField;
    // End of variables declaration//GEN-END:variables
}
